services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
            target: develop
        tty: true
        environment:
            - PORT=8080
        ports:
            - 8080:8080
        volumes:
            - ./:/app
